---
- name: Install client package
  ansible.builtin.package:
    name: redis-tools
    state: present
  tags:
    - redis

- name: Create defined group
  register: redis_group_result
  ansible.builtin.group:
    name: "{{ redis_group }}"
    system: true
    state: present
  tags:
    - redis

- name: Create defined user
  register: redis_user_result
  ansible.builtin.user:
    name: "{{ redis_user }}"
    group: "{{ redis_group }}"
    comment: redis
    password: "!"
    shell: /usr/sbin/nologin
    home: "{{ redis_volume_server }}"
    createhome: false
    system: true
    state: present
  tags:
    - redis

- name: Create data dir
  ansible.builtin.file:
    path: "{{ redis_volume_server }}"
    state: directory
    owner: "{{ redis_user_result.uid }}"
    group: "{{ redis_group_result.gid }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - redis

- name: Write default config
  notify:
    - Restart redis
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/redis
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - redis

- name: Write service file
  notify:
    - Restart redis
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/redis.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - redis

- name: Pull docker image
  when:
    - redis_pull_image
  community.docker.docker_image:
    name: "{{ redis_image }}"
    source: pull
  tags:
    - redis

- name: Create docker network
  when:
    - redis_network is not none
    - redis_network | length > 0
  community.docker.docker_network:
    name: "{{ redis_network }}"
  tags:
    - redis

- name: Start redis service
  ansible.builtin.systemd:
    name: redis
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - redis

...
